name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)
trigger:
  batch: 'true'
  branches:
    include:
      - master
      - feature/*
pool:
  vmImage: 'ubuntu-latest'

variables:
- name: TF_VERSION
  value: '0.12.24'

stages:
- template: templates/lint.yml
  parameters:
    service_connection: 'azure-msdn-outlook-sub-sc'
    states: 
      infrastructure:
        - default

# Plan NonProd
- template: templates/plan.yml
  parameters:
    service_connection: 'azure-msdn-outlook-sub-sc'
    states: 
      infrastucture:
        workspaces:
          - default

# Apply NonProd
- template: templates/apply.yml
  parameters:
    service_connection: 'azure-msdn-outlook-sub-sc'
    states: 
      infrastucture:
        workspaces:
          - default